name: Build Documentation
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./doc/generic/pgf/
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Build in TeXLive environment
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add poppler-utils
            cd doc/generic/pgf/
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          pip install beautifulsoup4 html5lib requests
          npm install -g prettier
          npm install -g svgo
      - name: Build docs
        run: |
          ./build.sh
          sleep 30
      - name: Push to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: doc/generic/pgf/processed