name: Build Documentation
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./doc/generic/pgf/
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Build in TeXLive environment
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add poppler-utils pngquant
            cd doc/generic/pgf/
            ./latexbuild.sh
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: pgfmanual
          path: doc/generic/pgf/
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          sudo apt-get install poppler-utils
          pip install beautifulsoup4 html5lib requests
          npm install -g prettier
          npm install -g svgo
      - name: Postprocessing
        run: |
          python3 postprocessing.py
          svgo -f processed/pgfmanual-images
      - name: Push to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: doc/generic/pgf/processed