name: Build Documentation
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./doc/generic/pgf/
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Run in TeXLive environment
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            cd doc/generic/pgf/
            lualatex -interaction=nonstopmode -halt-on-error pgfmanual.tex
            lwarpmk cleanall
            lwarpmk html
            ./build-limages-with-margin.lua limages
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Postprocessing
        run: python postprocessing.py