name: Build Documentation
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./doc/generic/pgf/
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build in TeXLive environment
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            cd doc/generic/pgf/
            ./latexbuild.sh
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          cache: 'pip'
          architecture: 'x64'
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          pip install beautifulsoup4
          npm install -g prettier
          npm install -g svgo
      - name: Python postprocessing
        run: |
          python postprocessing.py